/**
 * @module ai/modules/patient-assistant.module
 * @description AI Patient Assistant Module — Self-service guidance, plain-language explanations, reminders, and translation.
 */

import { chatService } from '../services/chat.service.js';
import { promptManager } from '../prompts/prompt-manager.js';
import { tokenUsageTracker } from '../analytics/token-usage-tracker.js';
import { sanitizeUserInput } from '../utils/sanitize.js';

export interface PatientAssistantInput {
  tenantId: string;
  userId: string;
  patientQuery: string;
  medicalData?: string;
  targetLanguage?: string;
}

export interface PatientAssistantResult {
  explanation: string;
  targetLanguage: string;
  disclaimer: string;
  latencyMs: number;
}

export class AIPatientAssistantModule {
  async assistPatient(input: PatientAssistantInput): Promise<PatientAssistantResult> {
    const startMs = Date.now();
    const lang = input.targetLanguage ?? 'English';

    const messages = promptManager.render('ai-patient-assistant', {
      PATIENT_QUERY: sanitizeUserInput(input.patientQuery),
      MEDICAL_DATA: sanitizeUserInput(input.medicalData ?? 'No specific clinical attachments'),
      TARGET_LANGUAGE: lang,
    });

    const result = await chatService.complete(messages);
    const latencyMs = Date.now() - startMs;

    tokenUsageTracker.record({
      tenantId: input.tenantId,
      userId: input.userId,
      feature: 'patient-assistant',
      model: result.model,
      provider: result.provider,
      usage: result.usage,
      latencyMs,
      success: true,
    });

    return {
      explanation: result.content,
      targetLanguage: lang,
      disclaimer: 'This educational summary is generated by AI to help explain clinical documents in plain language. Please consult your treating physician for personal medical decisions.',
      latencyMs,
    };
  }
}

export const aiPatientAssistantModule = new AIPatientAssistantModule();
