-- Initial Renovia Hospital OS schema. Generated from prisma/schema.prisma.
CREATE TYPE "Role" AS ENUM ('SUPER_ADMIN','HOSPITAL_ADMIN','DOCTOR','RECEPTIONIST','NURSE','PHARMACIST','LABORATORY_TECHNICIAN','ACCOUNTANT','PATIENT');
CREATE TYPE "JobStatus" AS ENUM ('PENDING','PROCESSING','COMPLETED','FAILED','CANCELLED');
CREATE TABLE "Hospital" ("id" UUID NOT NULL, "name" TEXT NOT NULL, "slug" TEXT NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Hospital_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" UUID NOT NULL, "hospitalId" UUID, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "role" "Role" NOT NULL, "isActive" BOOLEAN NOT NULL DEFAULT true, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Session" ("id" UUID NOT NULL, "userId" UUID NOT NULL, "tokenHash" TEXT NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "revokedAt" TIMESTAMP(3), "userAgent" TEXT, "ipAddress" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LoginEvent" ("id" UUID NOT NULL, "userId" UUID, "email" TEXT NOT NULL, "success" BOOLEAN NOT NULL, "ipAddress" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "LoginEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Patient" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "medicalRecordNumber" TEXT NOT NULL, "firstName" TEXT NOT NULL, "lastName" TEXT NOT NULL, "dateOfBirth" DATE NOT NULL, "phone" TEXT, "email" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, "deletedAt" TIMESTAMP(3), CONSTRAINT "Patient_pkey" PRIMARY KEY ("id"));
CREATE TABLE "BackgroundJob" ("id" UUID NOT NULL, "hospitalId" UUID, "type" TEXT NOT NULL, "payload" JSONB NOT NULL, "status" "JobStatus" NOT NULL DEFAULT 'PENDING', "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "attempts" INTEGER NOT NULL DEFAULT 0, "maxAttempts" INTEGER NOT NULL DEFAULT 3, "lockedAt" TIMESTAMP(3), "lockedBy" TEXT, "completedAt" TIMESTAMP(3), "failureReason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "BackgroundJob_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Hospital_slug_key" ON "Hospital"("slug"); CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash"); CREATE UNIQUE INDEX "Patient_hospitalId_medicalRecordNumber_key" ON "Patient"("hospitalId","medicalRecordNumber");
CREATE INDEX "User_hospitalId_role_idx" ON "User"("hospitalId","role"); CREATE INDEX "Session_userId_revokedAt_idx" ON "Session"("userId","revokedAt"); CREATE INDEX "LoginEvent_email_createdAt_idx" ON "LoginEvent"("email","createdAt"); CREATE INDEX "Patient_hospitalId_lastName_firstName_idx" ON "Patient"("hospitalId","lastName","firstName"); CREATE INDEX "Patient_hospitalId_deletedAt_createdAt_idx" ON "Patient"("hospitalId","deletedAt","createdAt"); CREATE INDEX "BackgroundJob_status_runAt_idx" ON "BackgroundJob"("status","runAt"); CREATE INDEX "BackgroundJob_hospitalId_status_runAt_idx" ON "BackgroundJob"("hospitalId","status","runAt");
ALTER TABLE "User" ADD CONSTRAINT "User_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "LoginEvent" ADD CONSTRAINT "LoginEvent_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE; ALTER TABLE "Patient" ADD CONSTRAINT "Patient_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE; ALTER TABLE "BackgroundJob" ADD CONSTRAINT "BackgroundJob_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
