CREATE TYPE "InventoryItemType" AS ENUM ('EQUIPMENT', 'CONSUMABLE');
CREATE TYPE "InventoryItemStatus" AS ENUM ('ACTIVE', 'RETIRED');
CREATE TYPE "ReminderType" AS ENUM ('APPOINTMENT', 'PAYMENT', 'PRESCRIPTION');
CREATE TYPE "ReminderStatus" AS ENUM ('SCHEDULED', 'SENT', 'FAILED', 'CANCELLED');
ALTER TABLE "FileObject" ADD COLUMN IF NOT EXISTS "labTestId" UUID;
ALTER TABLE "FileObject" ADD COLUMN IF NOT EXISTS "category" TEXT;
CREATE INDEX IF NOT EXISTS "FileObject_hospitalId_labTestId_idx" ON "FileObject"("hospitalId", "labTestId");
CREATE TABLE "MedicineBatch" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "medicineId" UUID NOT NULL, "batchNumber" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 0, "expiresAt" TIMESTAMP(3), "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "MedicineBatch_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "MedicineBatch_hospitalId_medicineId_batchNumber_key" ON "MedicineBatch"("hospitalId", "medicineId", "batchNumber");
CREATE INDEX "MedicineBatch_hospitalId_expiresAt_idx" ON "MedicineBatch"("hospitalId", "expiresAt");
CREATE TABLE "DispenseRecord" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "patientId" UUID NOT NULL, "medicineId" UUID NOT NULL, "prescriptionId" UUID, "dispensedById" UUID NOT NULL, "quantity" INTEGER NOT NULL, "dispensedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "DispenseRecord_pkey" PRIMARY KEY ("id"));
CREATE INDEX "DispenseRecord_hospitalId_patientId_dispensedAt_idx" ON "DispenseRecord"("hospitalId", "patientId", "dispensedAt");
CREATE INDEX "DispenseRecord_hospitalId_medicineId_dispensedAt_idx" ON "DispenseRecord"("hospitalId", "medicineId", "dispensedAt");
CREATE TABLE "InventoryItem" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "name" TEXT NOT NULL, "type" "InventoryItemType" NOT NULL, "category" TEXT, "quantity" INTEGER NOT NULL DEFAULT 0, "reorderLevel" INTEGER NOT NULL DEFAULT 0, "unitCost" DECIMAL(12,2), "location" TEXT, "status" "InventoryItemStatus" NOT NULL DEFAULT 'ACTIVE', "supplierName" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "InventoryItem_pkey" PRIMARY KEY ("id"));
CREATE INDEX "InventoryItem_hospitalId_type_status_idx" ON "InventoryItem"("hospitalId", "type", "status");
CREATE INDEX "InventoryItem_hospitalId_quantity_idx" ON "InventoryItem"("hospitalId", "quantity");
CREATE TABLE "Receipt" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "invoiceId" UUID NOT NULL, "receiptNumber" TEXT NOT NULL, "amount" DECIMAL(12,2) NOT NULL, "issuedById" UUID NOT NULL, "issuedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Receipt_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Receipt_hospitalId_receiptNumber_key" ON "Receipt"("hospitalId", "receiptNumber");
CREATE UNIQUE INDEX "Receipt_hospitalId_invoiceId_key" ON "Receipt"("hospitalId", "invoiceId");
CREATE INDEX "Receipt_hospitalId_issuedAt_idx" ON "Receipt"("hospitalId", "issuedAt");
CREATE TABLE "PayrollIntegration" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "providerName" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'CONFIGURED', "configuration" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PayrollIntegration_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PayrollIntegration_hospitalId_providerName_key" ON "PayrollIntegration"("hospitalId", "providerName");
CREATE TABLE "Reminder" ("id" UUID NOT NULL, "hospitalId" UUID NOT NULL, "userId" UUID, "type" "ReminderType" NOT NULL, "status" "ReminderStatus" NOT NULL DEFAULT 'SCHEDULED', "subject" TEXT NOT NULL, "body" TEXT NOT NULL, "runAt" TIMESTAMP(3) NOT NULL, "backgroundJobId" UUID, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Reminder_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Reminder_backgroundJobId_key" ON "Reminder"("backgroundJobId");
CREATE INDEX "Reminder_hospitalId_status_runAt_idx" ON "Reminder"("hospitalId", "status", "runAt");
ALTER TABLE "FileObject" ADD CONSTRAINT "FileObject_labTestId_fkey" FOREIGN KEY ("labTestId") REFERENCES "LabTest"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "MedicineBatch" ADD CONSTRAINT "MedicineBatch_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "MedicineBatch" ADD CONSTRAINT "MedicineBatch_medicineId_fkey" FOREIGN KEY ("medicineId") REFERENCES "Medicine"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_patientId_fkey" FOREIGN KEY ("patientId") REFERENCES "Patient"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_medicineId_fkey" FOREIGN KEY ("medicineId") REFERENCES "Medicine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_prescriptionId_fkey" FOREIGN KEY ("prescriptionId") REFERENCES "Prescription"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "DispenseRecord" ADD CONSTRAINT "DispenseRecord_dispensedById_fkey" FOREIGN KEY ("dispensedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InventoryItem" ADD CONSTRAINT "InventoryItem_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Receipt" ADD CONSTRAINT "Receipt_issuedById_fkey" FOREIGN KEY ("issuedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PayrollIntegration" ADD CONSTRAINT "PayrollIntegration_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_hospitalId_fkey" FOREIGN KEY ("hospitalId") REFERENCES "Hospital"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Reminder" ADD CONSTRAINT "Reminder_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;